[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ekqS81gko96DVkrFsBkg2-bQiF3oAcHkXd02oHJQ1R4/"
type = "service_account"
project_id = "pure-night-444323-f5"
private_key_id = "9729b809a603f1735ddecc6195fd20eb0bc636c5"

# ⚠️ 주의: 아래와 같이 반드시 줄바꿈이 포함된 형태로 입력해야 합니다.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQ8bxt5ZVYNRkJ
XYPFpJeb/TquKcjdvP/CHwbk+9xUZWPxee8TlKyTS+xryYahaJzHYAvu1VhhD9X6
nf74jEbHGUx58rnQSCzQQ/6nJzwgmvOUU9iHB/v+6ZUVoHANIySzVSbH9WgIytaf
zWc6/T1R36A/c2viky/33uQ2kjw0dLkyVFHvBnm6y0qRNRqFOY0XgJEj9/+2DEAa
ZXPTOYFgPmv6Kr0dIfKkTKBNba2EyqPFBb7pCA/HD7IwE3J8zg+5+RkdKEeX9Y4Y
xxykRHAZfTlWOwtszaLFy04Iyjtyl01WKypKRGepYWeQmF6kFKpNKvMtiNXXA6MX
fRwBuu11AgMBAAECggEABacDJYebBexvzYlOWIaBRHVyBNv5WghJdJ9WwNM7F2cO
cFilBKcBESiyEAtpsoxMMMzoHbv/R1GV72ZJS2uDZFJKokI++m5iv01A7RWFDU5r
zaTZXB51l881WtpWKwDQTBqpsSnyIx9roB3pekF3YHONLVI/xlIcL4IuiHcQcmHJ
Ilxd3pxRSLqi6MIzZTRXWT9DHD3oO2W5DlKv3rgmqMQ0iGv2p7DgerlYGPAaQuij
oFQ/M+rfjjTIO18q0gXnjU8XmY1C3R0FlUu1b9ztylS3xJbWNgZ2pTLlU77+ZvbF
CvsgPySNdKx9c2tkK3UZ9dkvDKOrmSo/YKmU3d3wgQKBgQDnv4FUmK7uJ3R92oBy
X0cNI5mxeCtRCruVB/MBXXYBoejsEusUsoBZgZJ1yrjbLxJza15KFVWAj1pFEdvp
J7VgvV+q88q29Yz+IG3ZJ8FY+Jpu6ogBsWbbWR5Oupj+3Oa95TyYkn0Blq+ldtg9
c3keQi0HIAihRDwlL3aHuPQGgQKBgQDmz1IrDbVbXXFx0f4SR7OVif8Obi0woPMC
yQkMD77lWWXCz96He/dO2qCiSyIyLN6/z6GIFHWqMikxE2C4ra+vhX0ndaNYDLxU
xUA82IwLdINtfpBaGHykaM6pXroyo75NCA2FZLuUiRT2qU1ALCDY7avDn6gk9FDw
ANfsaJ609QKBgQC59zTjG7qUJVkXfPVB0i8D3iOBA/tOhxxL1RstZ0BAwxpUBkJa
U3snWBCdMVXxnO5jbC83p7L6/Q3lCxW7HUAxJwXT+toawySm8IL1lS9UI/pZMx58
rUzqi7MEXjxTmBQZIhDkJfjmA3NjheC0PytcGqJja1NBha318QZelw5LAQKBgD4Z
r/D3ikEf3iMSrfp7Ij1s2JwoVq5Lz7aDIpUFM4Z/zBpjVWs8lmi3+BpSfsvjOLeB
BOQZJSN6xYx3u0FVMfzWvLq+MwnAu3dPbx4v4VY/rhDqyaoEBp0xudDmNNDlL5GI
RiMK3FF1pJdNLATFGr1jDSDgNxxiQ9ifUXlBGNp1AoGBAK4/Xgl7Lr83II18vuHv
87ym1TaFCqcZEYSLcu9pp83l5Di/j/RPyFLy0o0r8HGVNNWO5thfmFSJTMRxfpFM
wmAfcb6k1JG4PD1ckO63Tp5sRGbXXafxZZyAHyI1YgEzowDZ3YjTQzza1JWvKX3c
D0FZeEh9KvRNKi2KJxKjzogi
-----END PRIVATE KEY-----"""

client_email = "re-calculator@pure-night-444323-f5.iam.gserviceaccount.com"
client_id = "116877419912037428910"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/re-calculator%40pure-night-444323-f5.iam.gserviceaccount.com"
